/* =========================================================================
   CedrickStore — Datos semilla: TIENDA DE STREAMING
   Cuentas de streaming, combos y servicios digitales.
   Logos originales de cada plataforma incluidos.
   ========================================================================= */
window.CEDRICK_SEED = (function () {

  var categories = [
    { id: 'streaming', name: 'Streaming Video', icon: 'chip', color: '#e50914' },
    { id: 'musica', name: 'Música', icon: 'headset', color: '#1DB954' },
    { id: 'combos', name: 'Combos', icon: 'box', color: '#c9a227' },
    { id: 'herramientas', name: 'Herramientas', icon: 'sparkle', color: '#00c4cc' },
    { id: 'iptv', name: 'IPTV / TV en vivo', icon: 'home', color: '#9b59f6' },
    { id: 'anime', name: 'Anime', icon: 'star', color: '#f47521' }
  ];

  var brands = [
    { id: 'netflix', name: 'Netflix' },
    { id: 'disney', name: 'Disney+' },
    { id: 'prime', name: 'Prime Video' },
    { id: 'hbo', name: 'HBO Max' },
    { id: 'paramount', name: 'Paramount+' },
    { id: 'apple', name: 'Apple TV+' },
    { id: 'crunchyroll', name: 'Crunchyroll' },
    { id: 'spotify', name: 'Spotify' },
    { id: 'vix', name: 'ViX' },
    { id: 'youtube', name: 'YouTube Premium' },
    { id: 'canva', name: 'Canva Pro' },
    { id: 'iptv', name: 'IPTV Smarters' },
    { id: 'plex', name: 'Plex' },
    { id: 'cedrick', name: 'CedrickStore' }
  ];

  var coupons = [
    { code: 'CEDRICK10', type: 'percent', value: 10, label: '10% de descuento' },
    { code: 'STREAMING20', type: 'percent', value: 20, label: '20% de descuento' },
    { code: 'BIENVENIDO', type: 'fixed', value: 5000, label: '$5.000 de descuento' }
  ];

  var banners = [
    { id: 'b1', eyebrow: 'Tu entretenimiento premium', title: 'Todas las plataformas de <span>streaming</span> al mejor precio', text: 'Netflix, Disney+, HBO Max, Spotify y mas. Cuentas con garantia de 30 dias. Entrega inmediata.', cta: 'Ver catalogo', link: 'catalog.html', badge: '-60%', tone: 'dark', icon: 'chip' },
    { id: 'b2', eyebrow: 'Combos desde $14.000', title: 'Arma tu <span>combo</span> perfecto y ahorra', text: '28 combos disponibles. Netflix + Disney + HBO y mucho mas. 1 pantalla por 30 dias garantizado.', cta: 'Ver combos', link: 'catalog.html?cat=combos', badge: 'TOP', tone: 'gold', icon: 'box' },
    { id: 'b3', eyebrow: 'Entrega inmediata', title: 'Paga y recibe tu <span>cuenta</span> al instante', text: 'Pedido por WhatsApp o pago con monedero. Soporte 24/7.', cta: 'Comprar ahora', link: 'digital.html', badge: '24/7', tone: 'blue', icon: 'sparkle' }
  ];

  var testimonials = [
    { name: 'Laura M.', role: 'Cliente verificada', rating: 5, text: 'Compre el combo Netflix + Disney y en 2 minutos ya tenia mis cuentas. Funcionan perfecto!' },
    { name: 'Andres G.', role: 'Cliente frecuente', rating: 5, text: 'Llevo 6 meses comprando aqui. Nunca he tenido problemas. El soporte por WhatsApp es excelente.' },
    { name: 'Valentina R.', role: 'Cliente verificada', rating: 5, text: 'Los precios son increibles. La cuenta de Spotify funciona genial.' },
    { name: 'Sebastian C.', role: 'Cliente nuevo', rating: 4, text: 'Pedi HBO Max y me llego al instante. Muy buena atencion.' }
  ];

  // LOGOS OFICIALES de cada plataforma (URLs publicas)
  var LOGOS = {
    netflix: 'https://images.ctfassets.net/y2ske730sjqp/1aONibCke6niZhgPxuiilC/2c401b05a07288746ddf3bd1571c57d4/BrandAssets_Logos_01-Wordmark.jpg',
    disney: 'https://cnbl-cdn.bamgrid.com/assets/7ecc8bcb60ad77193058d63e321bd21cbac2fc67/original',
    prime: 'https://m.media-amazon.com/images/G/01/digital/video/acquisition/web_footer_logo._CB462908456_.png',
    hbo: 'https://play-lh.googleusercontent.com/1iyX7VdQ7MlM7iotI9XDtTwgiVmqFGzqwz10L67XVoyiTmJVoHCiR0JHogmRuL9MBfY',
    paramount: 'https://play-lh.googleusercontent.com/xoGGYH2LgLibLDBoxMg-ZE16b-RNfITw_OgXBWRAPin2FZY4FGB9QKBYApHO9Tn0OQ',
    crunchyroll: 'https://play-lh.googleusercontent.com/a-0bNNz1fHIl-DUnRWiXco4O6uPIp_IFbJKqMC7-ice_nazuaBDuKEMRSQYOGePDAOcMM',
    apple: 'https://play-lh.googleusercontent.com/Xu7HBXAQ4VJQiIoWNeUXMq_9LOaR3Bn1d3E_iXLSYJsjFF7lNi6u-Ci0lU7TalGlGQk',
    spotify: 'https://storage.googleapis.com/pr-newsroom-wp/1/2023/05/Spotify_Primary_Logo_RGB_Green.png',
    vix: 'https://play-lh.googleusercontent.com/HFP9-GDmXNbJfmx9RGmGJhHsO0pM-H7Y-frF9bPsJwZtNeMbd2ZWpw1GITsWw9bKFs',
    youtube: 'https://play-lh.googleusercontent.com/lMoItBgdPPVDJsNOVtP26EKHePkwBg-PkuY9NOrc-fumRtTFP4XhpUNk_22syN4Datc',
    canva: 'https://play-lh.googleusercontent.com/Gqu1aMEkQGkacfZ_k2PirKOSMDnFnYQFOcG7K_9HZQbFBYwVjwm3oZN1F0Mfnr0f3Q',
    iptv: 'https://play-lh.googleusercontent.com/bFaBJwTm3e5FLjifEJ8QrJWO6bVgxUDyS0Lae-hD7QGkE5xJhHPBmTZFKHwC1_S_Ug',
    plex: 'https://play-lh.googleusercontent.com/AzfRh7V5wopaaFYPNbvF8LGGIr_Hfm3MNC9S_eFQzs7Kj21e-0gWjJlh6v_9gpnLcE'
  };

  var products = [
    { id: 'netflix', name: 'Netflix - 1 Pantalla', category: 'streaming', brand: 'netflix', price: 15000, oldPrice: 45000, stock: 50, rating: 4.9, sold: 892, featured: true, bestseller: true, tone: '#e50914', image: LOGOS.netflix, desc: 'Cuenta de Netflix con 1 pantalla por 30 dias. Miles de peliculas, series y documentales en HD. Perfil propio garantizado.', gallery: 2, specs: { 'Pantallas': '1', 'Calidad': 'HD', 'Duracion': '30 dias', 'Garantia': '30 dias', 'Entrega': 'Inmediata' }, reviews: [] },
    { id: 'disney', name: 'Disney+ Star - 1 Pantalla', category: 'streaming', brand: 'disney', price: 15000, oldPrice: 40000, stock: 50, rating: 4.8, sold: 756, featured: true, bestseller: true, tone: '#0063e5', image: LOGOS.disney, desc: 'Disney+ con Star incluido. 1 pantalla por 30 dias. Disney, Marvel, Star Wars, Pixar y National Geographic.', gallery: 2, specs: { 'Pantallas': '1', 'Contenido': 'Disney + Star', 'Duracion': '30 dias', 'Garantia': '30 dias', 'Entrega': 'Inmediata' }, reviews: [] },
    { id: 'prime', name: 'Prime Video - 1 Pantalla TV', category: 'streaming', brand: 'prime', price: 10000, oldPrice: 30000, stock: 50, rating: 4.7, sold: 634, featured: true, bestseller: true, tone: '#00a8e1', image: LOGOS.prime, desc: 'Amazon Prime Video para TV. 1 pantalla por 30 dias. The Boys, Rings of Power, Jack Ryan y mas.', gallery: 2, specs: { 'Pantallas': '1 (TV)', 'Duracion': '30 dias', 'Garantia': '30 dias', 'Entrega': 'Inmediata' }, reviews: [] },
    { id: 'hbo', name: 'HBO Max - 1 Pantalla', category: 'streaming', brand: 'hbo', price: 12000, oldPrice: 35000, stock: 50, rating: 4.8, sold: 543, featured: true, bestseller: true, tone: '#b535f6', image: LOGOS.hbo, desc: 'HBO Max con todo el contenido de HBO, Warner Bros, DC. House of the Dragon, The Last of Us, Succession.', gallery: 2, specs: { 'Pantallas': '1', 'Duracion': '30 dias', 'Garantia': '30 dias', 'Entrega': 'Inmediata' }, reviews: [] },
    { id: 'paramount', name: 'Paramount+ - 1 Pantalla', category: 'streaming', brand: 'paramount', price: 8000, oldPrice: 25000, stock: 50, rating: 4.6, sold: 412, bestseller: true, tone: '#0064ff', image: LOGOS.paramount, desc: 'Paramount+ con peliculas y series exclusivas. Yellowstone, Star Trek, South Park, Halo.', gallery: 2, specs: { 'Pantallas': '1', 'Duracion': '30 dias', 'Garantia': '30 dias', 'Entrega': 'Inmediata' }, reviews: [] },
    { id: 'crunchyroll', name: 'Crunchyroll - 1 Pantalla', category: 'anime', brand: 'crunchyroll', price: 8000, oldPrice: 22000, stock: 50, rating: 4.7, sold: 398, bestseller: true, tone: '#f47521', image: LOGOS.crunchyroll, desc: 'Crunchyroll Premium. La mayor biblioteca de anime del mundo. Simulcasts, manga y mas.', gallery: 2, specs: { 'Pantallas': '1', 'Contenido': 'Anime + Manga', 'Duracion': '30 dias', 'Garantia': '30 dias', 'Entrega': 'Inmediata' }, reviews: [] },
    { id: 'apple', name: 'Apple TV+ - 1 Pantalla', category: 'streaming', brand: 'apple', price: 13000, oldPrice: 35000, stock: 50, rating: 4.7, sold: 287, featured: true, tone: '#333333', image: LOGOS.apple, desc: 'Apple TV+ con contenido original premium. Ted Lasso, Severance, The Morning Show, Foundation.', gallery: 2, specs: { 'Pantallas': '1', 'Calidad': '4K HDR', 'Duracion': '30 dias', 'Garantia': '30 dias', 'Entrega': 'Inmediata' }, reviews: [] },
    { id: 'spotify', name: 'Spotify Premium - 1 Mes', category: 'musica', brand: 'spotify', price: 15000, oldPrice: 35000, stock: 50, rating: 4.9, sold: 1024, featured: true, bestseller: true, tone: '#1DB954', image: LOGOS.spotify, desc: 'Spotify Premium individual por 1 mes. Musica sin anuncios, descarga offline, calidad alta.', gallery: 2, specs: { 'Tipo': 'Individual', 'Sin anuncios': 'Si', 'Offline': 'Si', 'Duracion': '30 dias', 'Garantia': '30 dias', 'Entrega': 'Inmediata' }, reviews: [] },
    { id: 'vix', name: 'ViX Premium - 1 Pantalla', category: 'streaming', brand: 'vix', price: 10000, oldPrice: 25000, stock: 50, rating: 4.5, sold: 312, tone: '#ff6b00', image: LOGOS.vix, desc: 'ViX Premium con contenido latino exclusivo. Novelas, deportes, peliculas y series en espanol.', gallery: 2, specs: { 'Pantallas': '1', 'Contenido': 'Latino', 'Duracion': '30 dias', 'Garantia': '30 dias', 'Entrega': 'Inmediata' }, reviews: [] },
    { id: 'youtube', name: 'YouTube Premium - 1 Mes', category: 'streaming', brand: 'youtube', price: 12000, oldPrice: 32000, stock: 50, rating: 4.8, sold: 567, featured: true, bestseller: true, tone: '#ff0000', image: LOGOS.youtube, desc: 'YouTube sin anuncios. Videos sin interrupciones, segundo plano, YouTube Music incluido.', gallery: 2, specs: { 'Sin anuncios': 'Si', 'YouTube Music': 'Incluido', 'Segundo plano': 'Si', 'Duracion': '30 dias', 'Garantia': '30 dias', 'Entrega': 'Inmediata' }, reviews: [] },
    { id: 'canva', name: 'Canva Pro - 1 Mes', category: 'herramientas', brand: 'canva', price: 10000, oldPrice: 28000, stock: 50, rating: 4.8, sold: 445, featured: true, tone: '#00c4cc', image: LOGOS.canva, desc: 'Canva Pro por 1 mes. Disenos ilimitados, plantillas premium, fondos removibles, marca kit.', gallery: 2, specs: { 'Plantillas': 'Ilimitadas', 'Almacenamiento': '100 GB', 'Duracion': '30 dias', 'Garantia': '30 dias', 'Entrega': 'Inmediata' }, reviews: [] },
    { id: 'iptv-sm', name: 'IPTV Smarters - 1 Mes', category: 'iptv', brand: 'iptv', price: 15000, oldPrice: 40000, stock: 50, rating: 4.6, sold: 389, featured: true, bestseller: true, tone: '#9b59f6', image: LOGOS.iptv, desc: 'IPTV Smarters Pro con +5000 canales en vivo. Deportes, peliculas, series, novelas. Smart TV, celular, PC.', gallery: 2, specs: { 'Canales': '+5000', 'Deportes': 'Si (incluye PPV)', 'Dispositivos': 'TV, Celular, PC', 'Duracion': '30 dias', 'Garantia': '30 dias', 'Entrega': 'Inmediata' }, reviews: [] },
    { id: 'plex', name: 'Plex Premium - 1 Mes', category: 'iptv', brand: 'plex', price: 12000, oldPrice: 30000, stock: 50, rating: 4.5, sold: 234, tone: '#e5a00d', image: LOGOS.plex, desc: 'Plex Premium. Peliculas y series on demand, TV en vivo, sincronizacion entre dispositivos, hasta 4K.', gallery: 2, specs: { 'Contenido': 'On demand + TV en vivo', 'Calidad': 'Hasta 4K', 'Duracion': '30 dias', 'Garantia': '30 dias', 'Entrega': 'Inmediata' }, reviews: [] },
    { id: 'combo1', name: 'Combo #1 - Netflix + Disney+ Star', category: 'combos', brand: 'cedrick', price: 23000, oldPrice: 30000, stock: 30, rating: 4.9, sold: 234, featured: true, bestseller: true, tone: '#c9a227', image: LOGOS.netflix, desc: '1 pantalla de Netflix + 1 pantalla de Disney+ Star. 30 dias garantizado.', gallery: 2, specs: { 'Netflix': '1 pantalla', 'Disney+ Star': '1 pantalla', 'Duracion': '30 dias', 'Garantia': '30 dias' }, reviews: [] },
    { id: 'combo2', name: 'Combo #2 - Netflix + Prime Video', category: 'combos', brand: 'cedrick', price: 23000, oldPrice: 30000, stock: 30, rating: 4.8, sold: 198, tone: '#c9a227', image: LOGOS.netflix, desc: '1 pantalla de Netflix + 1 pantalla de Prime Video. 30 dias garantizado.', gallery: 2, specs: { 'Netflix': '1 pantalla', 'Prime Video': '1 pantalla', 'Duracion': '30 dias', 'Garantia': '30 dias' }, reviews: [] },
    { id: 'combo3', name: 'Combo #3 - Netflix + HBO Max', category: 'combos', brand: 'cedrick', price: 20000, oldPrice: 27000, stock: 30, rating: 4.8, sold: 187, tone: '#c9a227', image: LOGOS.netflix, desc: '1 pantalla de Netflix + 1 pantalla de HBO Max. 30 dias garantizado.', gallery: 2, specs: { 'Netflix': '1 pantalla', 'HBO Max': '1 pantalla', 'Duracion': '30 dias', 'Garantia': '30 dias' }, reviews: [] },
    { id: 'combo4', name: 'Combo #4 - Netflix + Crunchyroll', category: 'combos', brand: 'cedrick', price: 21000, oldPrice: 28000, stock: 30, rating: 4.7, sold: 156, tone: '#c9a227', image: LOGOS.netflix, desc: '1 pantalla de Netflix + 1 pantalla de Crunchyroll. 30 dias garantizado.', gallery: 2, specs: { 'Netflix': '1 pantalla', 'Crunchyroll': '1 pantalla', 'Duracion': '30 dias', 'Garantia': '30 dias' }, reviews: [] },
    { id: 'combo5', name: 'Combo #5 - Netflix + Paramount+', category: 'combos', brand: 'cedrick', price: 20000, oldPrice: 27000, stock: 30, rating: 4.7, sold: 145, tone: '#c9a227', image: LOGOS.netflix, desc: '1 pantalla de Netflix + 1 pantalla de Paramount+. 30 dias garantizado.', gallery: 2, specs: { 'Netflix': '1 pantalla', 'Paramount+': '1 pantalla', 'Duracion': '30 dias', 'Garantia': '30 dias' }, reviews: [] },
    { id: 'combo6', name: 'Combo #6 - Disney+ Star + Prime Video', category: 'combos', brand: 'cedrick', price: 19000, oldPrice: 25000, stock: 30, rating: 4.7, sold: 134, tone: '#c9a227', image: LOGOS.disney, desc: '1 pantalla de Disney+ Star + 1 pantalla de Prime Video. 30 dias garantizado.', gallery: 2, specs: { 'Disney+ Star': '1 pantalla', 'Prime Video': '1 pantalla', 'Duracion': '30 dias', 'Garantia': '30 dias' }, reviews: [] },
    { id: 'combo7', name: 'Combo #7 - Disney+ Star + HBO Max', category: 'combos', brand: 'cedrick', price: 16000, oldPrice: 22000, stock: 30, rating: 4.6, sold: 123, tone: '#c9a227', image: LOGOS.disney, desc: '1 pantalla de Disney+ Star + 1 pantalla de HBO Max. 30 dias garantizado.', gallery: 2, specs: { 'Disney+ Star': '1 pantalla', 'HBO Max': '1 pantalla', 'Duracion': '30 dias', 'Garantia': '30 dias' }, reviews: [] },
    { id: 'combo8', name: 'Combo #8 - Disney+ Star + Paramount+', category: 'combos', brand: 'cedrick', price: 16000, oldPrice: 22000, stock: 30, rating: 4.6, sold: 112, tone: '#c9a227', image: LOGOS.disney, desc: '1 pantalla de Disney+ Star + 1 pantalla de Paramount+. 30 dias garantizado.', gallery: 2, specs: { 'Disney+ Star': '1 pantalla', 'Paramount+': '1 pantalla', 'Duracion': '30 dias', 'Garantia': '30 dias' }, reviews: [] },
    { id: 'combo9', name: 'Combo #9 - Prime Video + HBO Max', category: 'combos', brand: 'cedrick', price: 16000, oldPrice: 22000, stock: 30, rating: 4.7, sold: 145, tone: '#c9a227', image: LOGOS.prime, desc: '1 pantalla de Prime Video + 1 pantalla de HBO Max. 30 dias garantizado.', gallery: 2, specs: { 'Prime Video': '1 pantalla', 'HBO Max': '1 pantalla', 'Duracion': '30 dias', 'Garantia': '30 dias' }, reviews: [] },
    { id: 'combo10', name: 'Combo #10 - Prime Video + Paramount+', category: 'combos', brand: 'cedrick', price: 16000, oldPrice: 22000, stock: 30, rating: 4.6, sold: 98, tone: '#c9a227', image: LOGOS.prime, desc: '1 pantalla de Prime Video + 1 pantalla de Paramount+. 30 dias garantizado.', gallery: 2, specs: { 'Prime Video': '1 pantalla', 'Paramount+': '1 pantalla', 'Duracion': '30 dias', 'Garantia': '30 dias' }, reviews: [] },
    { id: 'combo11', name: 'Combo #11 - HBO Max + Crunchyroll', category: 'combos', brand: 'cedrick', price: 14000, oldPrice: 20000, stock: 30, rating: 4.6, sold: 89, tone: '#c9a227', image: LOGOS.hbo, desc: '1 pantalla de HBO Max + 1 pantalla de Crunchyroll. 30 dias garantizado.', gallery: 2, specs: { 'HBO Max': '1 pantalla', 'Crunchyroll': '1 pantalla', 'Duracion': '30 dias', 'Garantia': '30 dias' }, reviews: [] },
    { id: 'combo12', name: 'Combo #12 - Netflix + Disney+ + Prime Video', category: 'combos', brand: 'cedrick', price: 32000, oldPrice: 45000, stock: 30, rating: 4.9, sold: 278, featured: true, bestseller: true, tone: '#c9a227', image: LOGOS.netflix, desc: 'Netflix + Disney+ Star + Prime Video. 1 pantalla de cada uno por 30 dias.', gallery: 2, specs: { 'Netflix': '1 pantalla', 'Disney+ Star': '1 pantalla', 'Prime Video': '1 pantalla', 'Duracion': '30 dias', 'Garantia': '30 dias' }, reviews: [] },
    { id: 'combo13', name: 'Combo #13 - Netflix + Disney+ + HBO Max', category: 'combos', brand: 'cedrick', price: 29000, oldPrice: 40000, stock: 30, rating: 4.8, sold: 198, tone: '#c9a227', image: LOGOS.netflix, desc: 'Netflix + Disney+ Star + HBO Max. 1 pantalla de cada uno por 30 dias.', gallery: 2, specs: { 'Netflix': '1 pantalla', 'Disney+ Star': '1 pantalla', 'HBO Max': '1 pantalla', 'Duracion': '30 dias', 'Garantia': '30 dias' }, reviews: [] },
    { id: 'combo14', name: 'Combo #14 - Netflix + Disney+ + Crunchyroll', category: 'combos', brand: 'cedrick', price: 30000, oldPrice: 42000, stock: 30, rating: 4.8, sold: 167, tone: '#c9a227', image: LOGOS.netflix, desc: 'Netflix + Disney+ Star + Crunchyroll. 1 pantalla de cada uno por 30 dias.', gallery: 2, specs: { 'Netflix': '1 pantalla', 'Disney+ Star': '1 pantalla', 'Crunchyroll': '1 pantalla', 'Duracion': '30 dias', 'Garantia': '30 dias' }, reviews: [] },
    { id: 'combo15', name: 'Combo #15 - Netflix + Prime + HBO Max', category: 'combos', brand: 'cedrick', price: 29000, oldPrice: 40000, stock: 30, rating: 4.8, sold: 212, tone: '#c9a227', image: LOGOS.netflix, desc: 'Netflix + Prime Video + HBO Max. 1 pantalla de cada uno por 30 dias.', gallery: 2, specs: { 'Netflix': '1 pantalla', 'Prime Video': '1 pantalla', 'HBO Max': '1 pantalla', 'Duracion': '30 dias', 'Garantia': '30 dias' }, reviews: [] },
    { id: 'combo16', name: 'Combo #16 - Netflix + Prime + Crunchyroll', category: 'combos', brand: 'cedrick', price: 30000, oldPrice: 42000, stock: 30, rating: 4.7, sold: 145, tone: '#c9a227', image: LOGOS.netflix, desc: 'Netflix + Prime Video + Crunchyroll. 1 pantalla de cada uno por 30 dias.', gallery: 2, specs: { 'Netflix': '1 pantalla', 'Prime Video': '1 pantalla', 'Crunchyroll': '1 pantalla', 'Duracion': '30 dias', 'Garantia': '30 dias' }, reviews: [] },
    { id: 'combo17', name: 'Combo #17 - Netflix + Prime + Paramount+', category: 'combos', brand: 'cedrick', price: 29000, oldPrice: 38000, stock: 30, rating: 4.7, sold: 134, tone: '#c9a227', image: LOGOS.netflix, desc: 'Netflix + Prime Video + Paramount+. 1 pantalla de cada uno por 30 dias.', gallery: 2, specs: { 'Netflix': '1 pantalla', 'Prime Video': '1 pantalla', 'Paramount+': '1 pantalla', 'Duracion': '30 dias', 'Garantia': '30 dias' }, reviews: [] },
    { id: 'combo18', name: 'Combo #18 - Disney+ + Prime + HBO Max', category: 'combos', brand: 'cedrick', price: 25000, oldPrice: 35000, stock: 30, rating: 4.7, sold: 123, tone: '#c9a227', image: LOGOS.disney, desc: 'Disney+ Star + Prime Video + HBO Max. 1 pantalla de cada uno por 30 dias.', gallery: 2, specs: { 'Disney+ Star': '1 pantalla', 'Prime Video': '1 pantalla', 'HBO Max': '1 pantalla', 'Duracion': '30 dias', 'Garantia': '30 dias' }, reviews: [] },
    { id: 'combo19', name: 'Combo #19 - Disney+ + Prime + Crunchyroll', category: 'combos', brand: 'cedrick', price: 26000, oldPrice: 36000, stock: 30, rating: 4.6, sold: 98, tone: '#c9a227', image: LOGOS.disney, desc: 'Disney+ Star + Prime Video + Crunchyroll. 1 pantalla de cada uno por 30 dias.', gallery: 2, specs: { 'Disney+ Star': '1 pantalla', 'Prime Video': '1 pantalla', 'Crunchyroll': '1 pantalla', 'Duracion': '30 dias', 'Garantia': '30 dias' }, reviews: [] },
    { id: 'combo20', name: 'Combo #20 - Disney+ + HBO Max + ViX', category: 'combos', brand: 'cedrick', price: 22000, oldPrice: 32000, stock: 30, rating: 4.6, sold: 87, tone: '#c9a227', image: LOGOS.disney, desc: 'Disney+ Star + HBO Max + ViX. 1 pantalla de cada uno por 30 dias.', gallery: 2, specs: { 'Disney+ Star': '1 pantalla', 'HBO Max': '1 pantalla', 'ViX': '1 pantalla', 'Duracion': '30 dias', 'Garantia': '30 dias' }, reviews: [] },
    { id: 'combo21', name: 'Combo #21 - HBO Max + ViX + Prime Video', category: 'combos', brand: 'cedrick', price: 22000, oldPrice: 32000, stock: 30, rating: 4.6, sold: 76, tone: '#c9a227', image: LOGOS.hbo, desc: 'HBO Max + ViX + Prime Video. 1 pantalla de cada uno por 30 dias.', gallery: 2, specs: { 'HBO Max': '1 pantalla', 'ViX': '1 pantalla', 'Prime Video': '1 pantalla', 'Duracion': '30 dias', 'Garantia': '30 dias' }, reviews: [] },
    { id: 'combo22', name: 'Combo #22 - Netflix + Disney+ + HBO + Prime', category: 'combos', brand: 'cedrick', price: 38000, oldPrice: 55000, stock: 30, rating: 4.9, sold: 312, featured: true, bestseller: true, tone: '#c9a227', image: LOGOS.netflix, desc: 'El combo TOP! Netflix + Disney+ Star + HBO Max + Prime Video. 1 pantalla de cada uno por 30 dias.', gallery: 2, specs: { 'Netflix': '1 pantalla', 'Disney+ Star': '1 pantalla', 'HBO Max': '1 pantalla', 'Prime Video': '1 pantalla', 'Duracion': '30 dias', 'Garantia': '30 dias' }, reviews: [] },
    { id: 'combo23', name: 'Combo #23 - Netflix + Disney+ + HBO + ViX', category: 'combos', brand: 'cedrick', price: 35000, oldPrice: 50000, stock: 30, rating: 4.8, sold: 167, tone: '#c9a227', image: LOGOS.netflix, desc: 'Netflix + Disney+ Star + HBO Max + ViX. 1 pantalla de cada uno por 30 dias.', gallery: 2, specs: { 'Netflix': '1 pantalla', 'Disney+ Star': '1 pantalla', 'HBO Max': '1 pantalla', 'ViX': '1 pantalla', 'Duracion': '30 dias', 'Garantia': '30 dias' }, reviews: [] },
    { id: 'combo24', name: 'Combo #24 - Netflix + Prime + HBO + Paramount+', category: 'combos', brand: 'cedrick', price: 35000, oldPrice: 48000, stock: 30, rating: 4.8, sold: 156, tone: '#c9a227', image: LOGOS.netflix, desc: 'Netflix + Prime Video + HBO Max + Paramount+. 1 pantalla de cada uno por 30 dias.', gallery: 2, specs: { 'Netflix': '1 pantalla', 'Prime Video': '1 pantalla', 'HBO Max': '1 pantalla', 'Paramount+': '1 pantalla', 'Duracion': '30 dias', 'Garantia': '30 dias' }, reviews: [] },
    { id: 'combo25', name: 'Combo #25 - Prime + Disney+ + ViX + Crunchyroll', category: 'combos', brand: 'cedrick', price: 31000, oldPrice: 43000, stock: 30, rating: 4.7, sold: 98, tone: '#c9a227', image: LOGOS.prime, desc: 'Prime Video + Disney+ Star + ViX + Crunchyroll. 1 pantalla de cada uno por 30 dias.', gallery: 2, specs: { 'Prime Video': '1 pantalla', 'Disney+ Star': '1 pantalla', 'ViX': '1 pantalla', 'Crunchyroll': '1 pantalla', 'Duracion': '30 dias', 'Garantia': '30 dias' }, reviews: [] },
    { id: 'combo26', name: 'Combo #26 - Disney+ + HBO + Prime + Crunchyroll', category: 'combos', brand: 'cedrick', price: 32000, oldPrice: 45000, stock: 30, rating: 4.7, sold: 89, tone: '#c9a227', image: LOGOS.disney, desc: 'Disney+ Star + HBO Max + Prime Video + Crunchyroll. 1 pantalla de cada uno por 30 dias.', gallery: 2, specs: { 'Disney+ Star': '1 pantalla', 'HBO Max': '1 pantalla', 'Prime Video': '1 pantalla', 'Crunchyroll': '1 pantalla', 'Duracion': '30 dias', 'Garantia': '30 dias' }, reviews: [] },
    { id: 'combo27', name: 'Combo #27 - HBO + ViX + Prime + Crunchyroll', category: 'combos', brand: 'cedrick', price: 28000, oldPrice: 40000, stock: 30, rating: 4.6, sold: 67, tone: '#c9a227', image: LOGOS.hbo, desc: 'HBO Max + ViX + Prime Video + Crunchyroll. 1 pantalla de cada uno por 30 dias.', gallery: 2, specs: { 'HBO Max': '1 pantalla', 'ViX': '1 pantalla', 'Prime Video': '1 pantalla', 'Crunchyroll': '1 pantalla', 'Duracion': '30 dias', 'Garantia': '30 dias' }, reviews: [] },
    { id: 'combo28', name: 'Combo #28 - Netflix + Prime + Crunchyroll + ViX + HBO', category: 'combos', brand: 'cedrick', price: 41000, oldPrice: 60000, stock: 30, rating: 4.9, sold: 245, featured: true, bestseller: true, tone: '#c9a227', image: LOGOS.netflix, desc: 'MEGA COMBO! Netflix + Prime Video + Crunchyroll + ViX + HBO Max. 1 pantalla de cada uno por 30 dias.', gallery: 2, specs: { 'Netflix': '1 pantalla', 'Prime Video': '1 pantalla', 'Crunchyroll': '1 pantalla', 'ViX': '1 pantalla', 'HBO Max': '1 pantalla', 'Duracion': '30 dias', 'Garantia': '30 dias' }, reviews: [] }
  ];

  return { categories: categories, brands: brands, coupons: coupons, banners: banners, testimonials: testimonials, products: products };
})();
